nameOverride: ""

image:
  repository: onos/mininet-kubernetes
  tag: 2.2.2
  pullPolicy: IfNotPresent
  pullSecrets: []

mininet:
  topo: "linear,4"
  switch: openvswitch

controller:
  service: onos
  replicas: 3
