nameOverride: ""

image:
  repository: atomix/atomix-kubernetes
  tag: 3.0.5
  pullPolicy: Never

atomix:
  replicas: 3
  logLevel: INFO
  heap: 2G
  partitionGroupName: raft
  partitionCount: 3
  partitionSize: 3

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
  # minAvailable: 1

persistence:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}

resources:
  requests:
    cpu: 0.5
    memory: 512Mi