nameOverride: ""

image:
  repository: onosproject/onos
  tag: 2.0.0
  pullPolicy: IfNotPresent
  pullSecrets: []

replicas: 3
heap: 4G
apps:
- org.onosproject.hostprovider
- org.onosproject.openflow
- org.onosproject.mcast

atomix:
  cluster:
    replicas: 3
    storage: {}
  raft:
    replicas: 3
    partitions: 3
    partitionSize: 3
    storage: {}
    compaction: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 0.5
    memory: 512Mi