nameOverride: ""

image:
  repository: onosproject/onos
  tag: 1.14.0
  pullPolicy: IfNotPresent
  pullSecrets: []

replicas: 3
heap: 4G

atomix:
  replicas: 3

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10

resources:
  requests:
    cpu: 0.5
    memory: 512Mi