# Headless service for stable DNS entries.
# The critical component of this service is support for publishing DNS entries before pods are ready.
# This is necessary for Atomix nodes to reach each other to form a quorum before transitioning to the ready state.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-hs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: {{ template "fullname" . }}-node
    port: 5679
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
---
# Client service for connecting to any Atomix instance REST API.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: {{ template "fullname" . }}-api
    port: 5678
  selector:
    app: {{ template "fullname" . }}