apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-init-scripts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  configure-onos.sh: |
    #!/usr/bin/env bash

    HOST=`hostname -s`

    function print_config() {
        echo "{"
        print_name
        print_node
        print_dns
        echo "}"
    }

    function print_name() {
        echo "  \"name\": \"onos\","
    }

    function print_node() {
        echo "  \"node\": {"
        echo "    \"id\": \"$HOST\","
        echo "    \"host\": \"$HOST\","
        echo "    \"port\": 9876"
        echo "  },"
    }

    function print_dns() {
        echo "  \"storageDnsService\": \"{{ template "fullname" }}-atomix\""
    }

    print_config
